Remove checks to support BL + APP updates
NordicSemiconductor/pc-nrfutil pull request #371
Opened 2022-03-01 11:46 UTC by br101

As explained in the Nordic Devzone ticket (*1) updates of APP+BL are necessary some times. There is no real reason why nrfutil forbids the creation of such packages. This commit removes these checks and I have successfully created an APP+BL package and updated my device.

(*1) https://devzone.nordicsemi.com/f/nordic-q-a/84879/feature-request-please-allow-app-bl-dfu-upgrades-in-nrfutil

2022-03-01 11:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NordicSemiconductor/pc-nrfutil?pullRequest=371) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NordicSemiconductor/pc-nrfutil?pullRequest=371) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NordicSemiconductor/pc-nrfutil?pullRequest=371) it.</sub>

2022-07-05 10:40 UTC, jornbh commented
The tests for test_init_command are failing for this PR. If you want this PR to be merged into master, "test_init_command_wrong_size()" should be updated so that the tests correspond to the new expected behavior.

2022-07-05 10:40 UTC, jornbh requested changes
The tests for test_init_command are failing for this PR. If you want this PR to be merged into master, "test_init_command_wrong_size()" should be updated so that the tests correspond to the new expected behavior.

2023-01-17 08:08 UTC, kenr commented
We do do not have capacity to maintain and release new versions of this utility.
The utility can be found here: https://www.nordicsemi.com/Products/Development-tools/nrf-util

2023-01-17 08:08 UTC, closed without merging